---
title: "Nobel winners"
author: "Ye Dam Yi"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_float: yes
---

```{r load-packages, message=FALSE}
library(tidyverse)
```

Let's first load the data:

```{r read-in-csv}
nobel <- read_csv(file = "data-raw/nobel.csv")
```

Then let's split the data into two:

```{r create-datasets}
# stem laureates
nobel_stem <- nobel %>%                                                       # create a dataset called nobel_stem
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))    # filters for the STEM fields

# non-steam laureates
nobel_nonstem <- nobel %>%
  filter(!category %in% c("Physics", "Medicine", "Chemistry", "Economics"))   # filters out the STEM fields (=filters for the remaining fields)

glimpse(nobel_stem)
glimpse(nobel_nonstem)

```

And finally write out the data:

```{r write-out-datasets}
write_csv(nobel_stem, file = "data/nobel_stem.csv")
write_csv(nobel_nonstem, file = "data/nobel_nonstem.csv")

```

## References {#references}
1. Assignment Adapted from [Mine Cetinkaya-Rundel's Data Science in a Box](https://github.com/rstudio-education/datascience-box)